### ISSUE TITLE
CI-building should use "npm ci" instead of "npm install"

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.VsCode.Recipe#14]
`npm install` will install the newest versions of all references given in the `package.json`, thus probably building a different version of the software between two runs.

At least in CI builds, the build should use [`npm ci`](https://docs.npmjs.com/cli/v6/commands/npm-ci) instead to ensure only the versions as given in `package-lock.json` are installed. (Thus ensuring deterministic builds.)

**Comment by gep13** [comment]
@nils-a I wasn't aware of the distinction.  It seems like the Npm Addin does have aliases for running `npm ci`, so it should be a simple enough switch over.
